# Generated by Django 4.0 on 2022-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
    ]
